Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [1]:
import numpy as np
import pandas as pd

In [2]:
zp=np.array([35,45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [5]:
ks =np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [6]:
c=(zp*ks).mean()-zp.mean()*ks.mean()
c

9157.839999999997

In [7]:
np.cov(zp,ks)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [8]:
np.cov(zp,ks)[0,1]

10175.377777777776

In [9]:
np.cov(zp,ks,ddof=0)[0,1] #смещенная оценка

9157.84

In [14]:
df=pd.DataFrame({'zp':zp,'ks':ks}, columns=['zp','ks'])
df

    zp   ks
0   35  401
1   45  574
2  190  874
3  200  919
4   40  459
5   70  739
6   54  653
7  150  902
8  120  746
9  110  832

In [16]:
df.cov().values[0,1] #несмещенная оценка

10175.377777777776

In [17]:
df.corr() #нахождение корелляции

         zp       ks
zp  1.00000  0.88749
ks  0.88749  1.00000

In [18]:
ks.std(ddof=1) #несмещенная оценка стандартного отклонения

183.99544076477068

In [19]:
zp.std(ddof=1)

62.31318747531162

In [21]:
df.cov().values[0,1]/(ks.std(ddof=1)*zp.std(ddof=1))

0.887490092073916

In [22]:
9157/(ks.std()*zp.std()) #при ddof=0

0.8874086873237411